# Generated by Django 2.0.3 on 2018-04-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='publication date')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('subject_name', models.CharField(max_length=30)),
                ('review_summary', models.CharField(max_length=50)),
            ],
        ),
    ]
