# Generated by Django 2.0.3 on 2018-04-19 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='subject_name',
            new_name='review_title',
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Subject'),
        ),
    ]
