# Generated by Django 2.0.3 on 2018-04-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180418_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(max_length=100),
        ),
    ]
